services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: vf
      POSTGRES_PASSWORD: vfpass
      POSTGRES_DB: voiceflow
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"


